name: upper_flutter_stores
description: >
  A lightweight, super-friendly, and non-verbose state management solution for Flutter.
version: 0.1.12
homepage: https://github.com/upperdo/upper_flutter_stores
repository: https://github.com/upperdo/upper_flutter_stores
issue_tracker: https://github.com/upperdo/upper_flutter_stores/issues
documentation: https://github.com/upperdo/upper_flutter_stores/blob/main/docs

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.4.0

topics:
  - state-management
  - flutter
  - dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  uses-material-design: true
