name: upper_flutter_stores
description: >
  A lightweight, super-friendly, and non-verbose state management solution for Flutter inspired by Svelte stores.
  Provides a unified API and modular stores for flexibility, performance, and scalability.
version: 0.1.6
homepage: https://github.com/upper/upper_flutter_store
repository: https://github.com/upper/upper_flutter_store
issue_tracker: https://github.com/upper/upper_flutter_store/issues
documentation: https://github.com/upper/upper_flutter_store#readme

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.4.0

topics:
  - state-management
  - flutter
  - dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  uses-material-design: true
